//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PostTypeID { get; set; }
        public string PostName { get; set; }
        public string PostTitle { get; set; }
        public string imageurl { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<int> BrowseVolume { get; set; }
    }
}
