//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCar
    {
        public int ShopCarID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsVaild { get; set; }
    }
}
