//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string Tel { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string ImageUrl { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> Vip { get; set; }
        public Nullable<System.DateTime> Lastlogin { get; set; }
    }
}
