//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityBackstage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdID { get; set; }
        public string AdName { get; set; }
        public string AdPwd { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string Grade { get; set; }
        public string State { get; set; }
        public string Power { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> Lastlogintime { get; set; }
    }
}
