//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityBackstage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string OrderState { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string ExpressNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceType { get; set; }
        public string AddressInfo { get; set; }
        public Nullable<bool> Isvaild { get; set; }
        public Nullable<decimal> PostMoney { get; set; }
        public string Note { get; set; }
    }
}
