//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCityBackstage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipAddress
    {
        public int ShipAddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Consignee { get; set; }
        public string Ctel { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<bool> IsValid { get; set; }
    }
}
